### ISSUE TITLE
Prompt Fusion not found in Scripts

### ISSUE THREAD

**Issue by fatualux** [ljleb/prompt-fusion-extension#57]
Hello, and thanks for your work.
I am on SdWebUI by Automatic1111, last update. I have installed this extension, enabled it in Settings, but I cannot figure how to try it out.
Unlike Prompt Travel it is not in the Scripts.
Maybe I have done some errors during the installation, or I have not understood how to make it work.

No errors shown in the shell, no traceback, I see prompt fusion among my installed extensions but I cannot found it anywhere in the UI.

I am on Arch Linux 6.4.8-arch1-1 x86_64, and stable diffusion runs in a virtual environment.

Please let me know if you need other information about my configuration.

Thanks in advance for your patience and support

**Comment by ljleb** [comment]
> Unlike Prompt Travel it is not in the Scripts.

This extension is purely syntactic. There is no additional user interface generated for it. To verify that it is working, have a look in the settings. If you see an additional section "Prompt Fusion" then it should be installed properly.

For more information on the syntax extension, please have a look at the wiki.

**Comment by fatualux** [comment]
Thank you for your clear explanation.

> To verify that it is working, have a look in the settings. If you see an additional section "Prompt Fusion" then it should be installed properly.

It seems to be all right, but I cannot make it work; I am a noob, but I do not want to give up with Prompt Fusion... surely there is something I did not understand.

Prompt travel the other extensions work, I cannot figure out what the problem is

https://github.com/ljleb/prompt-fusion-extension/assets/35587292/154cef9c-ae1e-4e38-a172-da06598101b5

**Comment by ljleb** [comment]
It seems to be working, I think it's just the steps points that are really too late in the process. for example, `[night light : magical forest : , 0.3 ]` should give you something closer to an in-between.

This is because the effect of a prompt at a particular step is much more important at the beginning of the prompt than at the end. You can think of it as being inverse proportional, although bevause of how samplers work I suspect this is a oversimplification of how it actually works.

**Comment by fatualux** [comment]
Ok, it works.
Thanks so much for your help :)
